site_name: Curriculum Compendium

theme:
  name: material
  features:
    - navigation.instant
    - search.highlight
    - navigation.indexes

markdown_extensions:
  # Content tabs and Admonitions
  - pymdownx.superfences
  # Content tabs
  - pymdownx.tabbed:
      alternate_style: true
  # Math
  - pymdownx.arithmatex:
      generic: true
  # Admonitions
  - admonition
  - pymdownx.details


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - stylesheets/admonitions/lemma.css
  - stylesheets/admonitions/theorem.css
  - stylesheets/admonitions/corollary.css
  - stylesheets/admonitions/definition.css
  - stylesheets/admonitions/proposition.css
  - stylesheets/admonitions/remark.css
  - stylesheets/admonitions/example.css
  - stylesheets/admonitions/proof.css